name: dotnet package

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK 5.0
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0.x'
    - name: Install dependencies
      run: dotnet restore
      working-directory: ./src
    - name: SonarScanner
      uses: highbyte/sonarscan-dotnet@2.0
      with:
        sonarProjectKey: SWeini_Cornucopia.Net
        sonarProjectName: Cornucopia.Net
        sonarOrganization: sweini
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      working-directory: ./src
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./src
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: ./src
    - uses: actions/upload-artifact@v2
      with:
        name: nuget
        path: ./src/**/*.nupkg
